name: Lint

on: [push, pull_request]

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: clang-format
        version: 1.0

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        clang_format: true
        clang_format_auto_fix: false
        clang_format_args: --style=Mozilla
        continue_on_error: true